version: '3.1'

services:
  payara:
    container_name: winderlebenpayara2
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8081:8080
      - 127.0.0.1:8182:8181
      - 127.0.0.1:4849:4848
      - 127.0.0.1:9009:9009
    
    environment:
      - TZ=Europe/Berlin
      - DATABASE_HOST=mysqldbtest
      - DATABASE_NAME=exampledb
      - DATABASE_USER=exampleuser
      - DATABASE_PORT=3306
      - PAYARA_ARGS=--debug

    secrets:
      - payaramysqlsecret

secrets:
  payaramysqlsecret:
    file: ./config/payara/payaradockersecrets