services:
  payara:
    container_name: winderlebenpayara
    image: payara/server-full:6.2023.12-jdk17
    restart: no
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8181:8181
      - 127.0.0.1:4848:4848
      - 127.0.0.1:9009:9009

    volumes:
      # # logs
      # - ./serverlog:/opt/payara/appserver/glassfish/domains/domain1/logs
      - ./config/resources/mysql-connector-j-8.1.0.jar:/opt/payara/appserver/glassfish/lib/mysql-connector-j-8.1.0.jar
      - ./config/payara/docker/pre-boot-commands.asadmin:/opt/payara/config/pre-boot-commands.asadmin
      - ./config/payara/docker/post-boot-commands.asadmin:/opt/payara/config/post-boot-commands.asadmin
      - ./app/build/libs/winderleben.war:/opt/payara/deployments/winderleben.war
      - ./config/payara/docker/restClientConfig.properties:/opt/payara/config/client.properties

    environment:
      - TZ=Europe/Berlin
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - PAYARA_ARGS=${PAYARA_ARGS}