services:
  payara:
    container_name: winderlebenpayara2
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 127.0.0.1:8081:8080
      - 127.0.0.1:8182:8181
      - 127.0.0.1:4849:4848
      - 127.0.0.1:9009:9009
    
    environment:
      - TZ=Europe/Berlin
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - PAYARA_ARGS=${PAYARA_ARGS}