services:
  payara:
    container_name: winderlebenpayara-prod
    image: schumidu2000/winderlebenscrapper:1.0
    restart: always
    ports: 
      - 127.0.0.1:4848:4848
    environment:
      - TZ=Europe/Berlin
    env_file: "prod.env"